spring:
  application:
    name: file-repository


  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB


  web:
    resources:
      cache:
        cachecontrol:
          max-age: 3600
          must-revalidate: false
          cache-public: true

filerepository:
  max-size: 10GB
  root:
    path: "${LOCAL_STORAGE_PATH:storage-files}"